server:
  port: 8090

spring:
  # springboot整合postgres连接配制
  datasource:
    primary:
      jdbc-url: jdbc:postgresql://localhost:5432/book
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver

    secondary:
      jdbc-url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

